# Generated by Django 5.2.10 on 2026-03-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Menejer'), ('staff', 'Xodim'), ('resident', 'Yashayotgan talaba'), ('applicant', 'Ariza beruvchi')], default='staff', max_length=20, verbose_name='Rol'),
        ),
    ]
