# Generated by Django 5.2.10 on 2026-03-15 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('buildings', '0005_add_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='building',
            field=models.ForeignKey(blank=True, help_text="Admin/Menejer/Xodim faqat shu binoni boshqara oladi. Bo'sh = barcha binolar.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_users', to='buildings.building', verbose_name='Biriktirilgan bino'),
        ),
    ]
