services:
  web:
    build: .
    container_name: yotoqxona_web
    restart: always
    volumes:
      - static_files:/app/staticfiles
      - media_files:/app/media
      - sqlite_data:/app/data
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    networks:
      - default
      - shared_net

  nginx:
    image: nginx:alpine
    container_name: yotoqxona_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_files:/app/staticfiles
      - media_files:/app/media
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
    depends_on:
      - web
    networks:
      - default
      - shared_net

  bot:
    build: .
    container_name: yotoqxona_bot
    restart: always
    command: python manage.py run_telegram_bot
    volumes:
      - sqlite_data:/app/data
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    depends_on:
      - web
    networks:
      - default

  certbot:
    image: certbot/certbot
    container_name: yotoqxona_certbot
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
    networks:
      - default

volumes:
  static_files:
  media_files:
  sqlite_data:
  certbot_www:
  certbot_conf:

networks:
  shared_net:
    external: true
