services:
  web:
    build: .
    container_name: yotoqxona_web
    restart: always
    volumes:
      - static_files:/app/staticfiles
      - media_files:/app/media
      - sqlite_data:/app/data
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    networks:
      - default
      - shared_net

  bot:
    build: .
    container_name: yotoqxona_bot
    restart: always
    command: python manage.py run_telegram_bot
    volumes:
      - sqlite_data:/app/data
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    depends_on:
      - web
    networks:
      - default

volumes:
  static_files:
  media_files:
  sqlite_data:

networks:
  shared_net:
    external: true
