# Generated by Django 5.2.10 on 2026-03-12 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Mazmuni')),
                ('category', models.CharField(choices=[('water', "Suv ta'minoti"), ('electricity', 'Elektr energiyasi'), ('gas', "Gaz ta'minoti"), ('internet', 'Internet'), ('maintenance', "Ta'mirlash ishlari"), ('rules', 'Qoidalar'), ('event', 'Tadbir'), ('general', 'Umumiy'), ('urgent', 'Shoshilinch')], default='general', max_length=20, verbose_name='Kategoriya')),
                ('priority', models.CharField(choices=[('low', 'Past'), ('normal', "O'rta"), ('high', 'Yuqori'), ('critical', 'Juda muhim')], default='normal', max_length=20, verbose_name='Muhimlik')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Amal qilish muddati')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='buildings.building', verbose_name="Bino (bo'sh = hammaga)")),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
            ],
            options={
                'verbose_name': "E'lon",
                'verbose_name_plural': "E'lonlar",
                'ordering': ['-created_at'],
            },
        ),
    ]
