# Generated by Django 5.2.10 on 2026-01-25 13:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Yil')),
                ('month', models.PositiveIntegerField(verbose_name='Oy')),
                ('total_invoiced', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Jami hisoblangan')),
                ('total_collected', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Jami yig'ilgan")),
                ('total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Jami qarzdorlik')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Moliyaviy hisobot',
                'verbose_name_plural': 'Moliyaviy hisobotlar',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('rent', "Ijara to'lovi"), ('deposit', 'Depozit'), ('utilities', 'Kommunal xizmatlar'), ('penalty', 'Jarima'), ('other', 'Boshqa')], default='rent', max_length=20, verbose_name='Turi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Summa')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Chiqarilgan sana')),
                ('due_date', models.DateField(verbose_name="To'lov muddati")),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='Davr boshi')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='Davr oxiri')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('partial', "Qisman to'langan"), ('paid', "To'langan"), ('overdue', "Muddati o'tgan"), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='students.student', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'Hisob-faktura',
                'verbose_name_plural': 'Hisob-fakturalar',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Summa')),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "O'tkazma"), ('other', 'Boshqa')], default='cash', max_length=20, verbose_name="To'lov usuli")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Bajarildi'), ('failed', 'Muvaffaqiyatsiz'), ('refunded', 'Qaytarildi')], default='completed', max_length=20, verbose_name='Holat')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="To'lov sanasi")),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referens')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.invoice', verbose_name='Hisob-faktura')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Qabul qiluvchi')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-payment_date'],
            },
        ),
    ]
