# Generated by Django 5.2.10 on 2026-01-25 13:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Otasining ismi')),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], default='male', max_length=10, verbose_name='Jinsi')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='Rasm')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, verbose_name='Favqulodda aloqa')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, verbose_name='Favqulodda telefon')),
                ('student_id', models.CharField(max_length=50, unique=True, verbose_name='Talaba ID')),
                ('faculty', models.CharField(blank=True, max_length=200, verbose_name='Fakultet')),
                ('group', models.CharField(blank=True, max_length=50, verbose_name='Guruh')),
                ('course', models.PositiveIntegerField(default=1, verbose_name='Kurs')),
                ('check_in_date', models.DateField(default=django.utils.timezone.now, verbose_name='Joylashgan sana')),
                ('check_out_date', models.DateField(blank=True, null=True, verbose_name='Chiqish sanasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='buildings.room', verbose_name='Xona')),
            ],
            options={
                'verbose_name': 'Talaba',
                'verbose_name_plural': 'Talabalar',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='RoomTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, verbose_name='Sabab')),
                ('transferred_at', models.DateTimeField(auto_now_add=True, verbose_name="Ko'chirilgan vaqt")),
                ('from_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='buildings.room', verbose_name='Qayerdan')),
                ('to_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='buildings.room', verbose_name='Qayerga')),
                ('transferred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='students.student', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': "Xona ko'chirish",
                'verbose_name_plural': "Xona ko'chirishlar",
                'ordering': ['-transferred_at'],
            },
        ),
    ]
