# Generated by Django 5.2.10 on 2026-03-12 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtransfer',
            name='from_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='buildings.room'),
        ),
        migrations.AlterField(
            model_name='roomtransfer',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='roomtransfer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='students.student'),
        ),
        migrations.AlterField(
            model_name='roomtransfer',
            name='to_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='buildings.room'),
        ),
        migrations.AlterField(
            model_name='roomtransfer',
            name='transferred_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='roomtransfer',
            name='transferred_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
