server {
    listen 80;
    server_name bekendchi.uz www.bekendchi.uz;

    location = /favicon.ico { access_log off; log_not_found off; }

    location /static/ {
        root /var/www/yotoqxona;
    }

    location /media/ {
        root /var/www/yotoqxona;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/yotoqxona.sock;
    }
}
