# Generated by Django 5.2.10 on 2026-01-25 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ikonka')),
            ],
            options={
                'verbose_name': 'Jihoz kategoriyasi',
                'verbose_name_plural': 'Jihoz kategoriyalari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Narxi')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.inventorycategory', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Jihoz turi',
                'verbose_name_plural': 'Jihoz turlari',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoomInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Soni')),
                ('condition', models.CharField(choices=[('new', 'Yangi'), ('good', 'Yaxshi'), ('fair', "O'rtacha"), ('poor', 'Yomon'), ('broken', 'Buzilgan')], default='good', max_length=20, verbose_name='Holati')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Seriya raqami')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Sotib olingan sana')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_items', to='inventory.inventoryitem', verbose_name='Jihoz')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='buildings.room', verbose_name='Xona')),
            ],
            options={
                'verbose_name': 'Xona jihozi',
                'verbose_name_plural': 'Xona jihozlari',
                'ordering': ['room', 'item__category', 'item__name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('added', "Qo'shildi"), ('removed', 'Olib tashlandi'), ('transferred', "Ko'chirildi"), ('repaired', "Ta'mirlandi"), ('replaced', 'Almashtirildi'), ('condition', "Holati o'zgardi")], max_length=20, verbose_name='Harakat')),
                ('old_value', models.CharField(blank=True, max_length=255, verbose_name='Eski qiymat')),
                ('new_value', models.CharField(blank=True, max_length=255, verbose_name='Yangi qiymat')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqti')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan')),
                ('room_inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='inventory.roominventory', verbose_name='Xona jihozi')),
            ],
            options={
                'verbose_name': 'Jihoz harakati',
                'verbose_name_plural': 'Jihozlar harakati',
                'ordering': ['-performed_at'],
            },
        ),
    ]
