# Generated by Django 5.2.10 on 2026-03-15 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_image_to_inventoryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inventory/', verbose_name='Rasm')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.inventoryitem', verbose_name='Jihoz')),
            ],
            options={
                'verbose_name': 'Jihoz rasmi',
                'verbose_name_plural': 'Jihoz rasmlari',
                'ordering': ['order', 'id'],
            },
        ),
    ]
