# Generated by Django 5.2.10 on 2026-01-25 13:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bino nomi')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bino',
                'verbose_name_plural': 'Binolar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Etaj raqami')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='buildings.building', verbose_name='Bino')),
            ],
            options={
                'verbose_name': 'Etaj',
                'verbose_name_plural': 'Etajlar',
                'ordering': ['building', 'number'],
                'unique_together': {('building', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Xona raqami')),
                ('room_type', models.CharField(choices=[('standard', 'Standart'), ('comfort', 'Komfort'), ('lux', 'Lyuks')], default='standard', max_length=20, verbose_name='Xona turi')),
                ('capacity', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name="Sig'imi (joy soni)")),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Oylik to'lov")),
                ('status', models.CharField(choices=[('available', "Bo'sh"), ('partial', "Qisman to'lgan"), ('full', "To'liq band"), ('maintenance', "Ta'mirda")], default='available', max_length=20, verbose_name='Holati')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='buildings.floor', verbose_name='Etaj')),
            ],
            options={
                'verbose_name': 'Xona',
                'verbose_name_plural': 'Xonalar',
                'ordering': ['floor__building', 'floor__number', 'number'],
                'unique_together': {('floor', 'number')},
            },
        ),
    ]
