# Generated by Django 5.2.10 on 2026-03-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Shahar'),
        ),
        migrations.AddField(
            model_name='building',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='buildings/', verbose_name='Rasm'),
        ),
        migrations.AddField(
            model_name='building',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name="Ko'cha"),
        ),
    ]
