# Generated by Django 5.2.10 on 2026-03-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_building_city_building_image_building_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='monthly_price',
        ),
        migrations.AddField(
            model_name='building',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Kunlik to'lov"),
        ),
        migrations.AddField(
            model_name='building',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Oylik to'lov"),
        ),
    ]
