# Generated by Django 5.2.10 on 2026-03-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_remove_room_monthly_price_building_daily_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Kenglik (latitude)'),
        ),
        migrations.AddField(
            model_name='building',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Uzunlik (longitude)'),
        ),
    ]
