# Generated by Django 5.2.10 on 2026-03-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_building_latitude_building_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='payment_deadline_day',
            field=models.PositiveIntegerField(default=10, verbose_name="To'lov muddati (har oyning nechanchisigacha)"),
        ),
        migrations.AddField(
            model_name='building',
            name='payment_terms',
            field=models.TextField(blank=True, help_text='Har bir shart yangi qatordan yoziladi', verbose_name="To'lov shartlari"),
        ),
    ]
