# Generated by Django 5.2.10 on 2026-03-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_add_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='gender',
            field=models.CharField(choices=[('male', 'Erkaklar'), ('female', 'Ayollar')], default='male', max_length=10, verbose_name='Jinsi'),
        ),
    ]
