# Generated by Django 5.2.10 on 2026-03-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0006_add_gender_to_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='gender',
            field=models.CharField(choices=[('male', 'Erkaklar'), ('female', 'Ayollar'), ('mixed', 'Aralash')], default='male', max_length=10, verbose_name='Jinsi'),
        ),
    ]
