# Generated by Django 5.2.10 on 2026-03-12 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Otasining ismi')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('student_id', models.CharField(max_length=50, verbose_name='Talaba ID')),
                ('faculty', models.CharField(blank=True, max_length=200, verbose_name='Fakultet')),
                ('group', models.CharField(blank=True, max_length=50, verbose_name='Guruh')),
                ('course', models.PositiveIntegerField(default=1, verbose_name='Kurs')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('payment_required', "To'lov kutilmoqda"), ('paid', "To'lov qilindi"), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi'), ('cancelled', 'Bekor qilindi')], default='pending', max_length=20, verbose_name='Holati')),
                ('message', models.TextField(blank=True, verbose_name='Xabar')),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin izohi')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="To'lov summasi")),
                ('payment_confirmed', models.BooleanField(default=False, verbose_name="To'lov tasdiqlandi")),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name="Ko'rib chiqilgan sana")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name="Ko'rib chiqqan")),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='buildings.room', verbose_name='Tanlangan xona')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
