# Generated by Django 5.2.10 on 2026-01-25 13:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('status', models.CharField(choices=[('present', 'Bor'), ('absent', "Yo'q"), ('late', 'Kechikkan'), ('excused', 'Sababli'), ('leave', "Ta'tilda")], default='present', max_length=20, verbose_name='Holat')),
                ('check_in_time', models.TimeField(blank=True, null=True, verbose_name='Kelish vaqti')),
                ('check_out_time', models.TimeField(blank=True, null=True, verbose_name='Ketish vaqti')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'Davomat',
                'verbose_name_plural': 'Davomat',
                'ordering': ['-date', 'student__last_name'],
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Yil')),
                ('month', models.PositiveIntegerField(verbose_name='Oy')),
                ('total_days', models.PositiveIntegerField(default=0, verbose_name='Jami kunlar')),
                ('present_days', models.PositiveIntegerField(default=0, verbose_name='Kelgan kunlar')),
                ('absent_days', models.PositiveIntegerField(default=0, verbose_name='Kelmagan kunlar')),
                ('late_days', models.PositiveIntegerField(default=0, verbose_name='Kechikkan kunlar')),
                ('excused_days', models.PositiveIntegerField(default=0, verbose_name='Sababli kunlar')),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Davomat foizi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_reports', to='students.student', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'Davomat hisoboti',
                'verbose_name_plural': 'Davomat hisobotlari',
                'ordering': ['-year', '-month'],
                'unique_together': {('student', 'year', 'month')},
            },
        ),
    ]
